pipeline {
    agent any

    parameters { string(name: 'Branch', defaultValue: 'develop', description: 'Enter the branch name') }

    tools {
        nodejs 'Node-23'
    }

    stages {
        stage("Npm Install & test") {
            steps {
                sh '''
                    node --version
                    cd assignmentOne
                    ls -ltr
                    npm i
                    npm test
                '''
                script {
                    def result = readJSON file: 'reports/jest-results.json'
                    def failedTests = result.numFailedTests
                    
                    if(failedTests > 0) {
                        echo '${failedTests} tests failed'
                    } else {
                        echo 'All ${result.numPassedTests} tests passed'
                    }
                }
            }
        }
    }
}