apiVersion: v1
kind: Service
metadata:
  name: python-website-service
  labels:
    app: python-website
spec:
  type: NodePort
  selector:
    app: python-website
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
