pipeline {
    agent any

    parameters { string(name: 'Branch', defaultValue: 'develop', description: 'Enter the branch name') }

    tools {
        nodejs 'Node-23'
    }

    environment {
        IMAGE_NAME = "assignmentone"
    }

    stages {
        stage("Npm Install & test") {
            steps {
                sh '''
                    node --version
                    cd assignment-1
                    ls -ltr
                    npm i
                    npm test
                '''
                script {
                    def result = readJSON file: 'assignment-1/reports/jest-results.json'
                    def failedTests = result.numFailedTests
                    
                    if(failedTests > 0) {
                        echo "${failedTests} tests failed"
                    } else {
                        echo "All ${result.numPassedTests} tests passed"
                    }
                }
            }
        }

        stage("Docker build") {
            steps {
                sh "docker ps"
                sh "ls -ltr"
                sh "docker build -t ${env.IMAGE_NAME} -f assignment-1/Dockerfile ."
            }
        }

        stage("Docker Run") {
            steps {
                sh "docker run -d -p 3000:3000 --name assignmentOne ${env.IMAGE_NAME}"
                sh 'sleep 5 && docker ps'
            }
        }
    }
}