name: CI/CD Python App on Minikube

on:
  push:
    branches: [ "develop" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and run tests
        run: |
          pip install -r assignment-4/requirements.txt
          python -m py_compile assignment-4/app.py

      - name: Build Docker image
        run: |
          docker build -t python-app:latest -f assignment-4/Dockerfile .

      - name: Tag image for Docker Hub
        run: |
          docker tag python-app:latest ${{ secrets.DOCKER_USERNAME }}/python-app:latest

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/python-app:latest


      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker

      - name: Deploy to Minikube
        run: |
          kubectl apply -f assignment-4/k8s/deployment.yml
          kubectl apply -f assignment-4/k8s/service.yml
          kubectl get pods
          kubectl rollout status deployment/python-app

      - name: Get Service URL
        run: minikube service python-service --url
